### ISSUE TITLE
Unable native ads with Colors.transparent background

### ISSUE THREAD

**Issue by pav3lo** [dreamsoftin/facebook_audience_network#65]
When I tried to use the native ads with a transparent color, it makes a exception:

child: FacebookNativeAd(
                      placementId: "YOUR_PLACEMENT_ID",
                      adType: NativeAdType.NATIVE_AD,
                      width: double.infinity,
                      height: 300,
                      backgroundColor: Colors.transparent, <--
...
);

E/AndroidRuntime(  738): FATAL EXCEPTION: 
E/AndroidRuntime(  738): java.lang.IllegalArgumentException: Unknown color
E/AndroidRuntime(  738): 	at android.graphics.Color.parseColor(Color.java:154)
E/AndroidRuntime(  738): 	at com.dsi.facebook_audience_network.FacebookNativeAdView.getViewAttributes(FacebookNativeAdPlugin.java:84)
E/AndroidRuntime(  738): 	at com.dsi.facebook_audience_network.FacebookNativeAdView.showNativeAd(FacebookNativeAdPlugin.java:168)
E/AndroidRuntime(  738): 	at com.dsi.facebook_audience_network.FacebookNativeAdView.access$000(FacebookNativeAdPlugin.java:42)
E/AndroidRuntime(  738): 	at com.dsi.facebook_audience_network.FacebookNativeAdView$1.run(FacebookNativeAdPlugin.java:149)
E/AndroidRuntime(  738): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(  738): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  738): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(  738): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(  738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  738): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(  738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by Omi231** [comment]
The workaround is use background color with 0.1 opacity.
