### ISSUE TITLE
PlayStore Published App Crashes on Launch if Native Ads are used

### ISSUE THREAD

**Issue by SachinGanesh** [dreamsoftin/facebook_audience_network#9]
If the app uses Native Ads, it will crash on launch

```E/AndroidRuntime: FATAL EXCEPTION: Thread-16
    Process: com.example.app, PID: 21546
    java.lang.RuntimeException: java.io.FileNotFoundException: audience_network.dex
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeLoader(DynamicLoaderFactory.java:109)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:83)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: audience_network.dex
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:755)
        at android.content.res.AssetManager.open(AssetManager.java:732)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.createInMemoryClassLoader(DynamicLoaderFactory.java:160)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeAdsSdkClassLoader(DynamicLoaderFactory.java:123)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeLoader(DynamicLoaderFactory.java:101)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:83) 
        at java.lang.Thread.run(Thread.java:764) ```

**Comment by SachinGanesh** [comment]
Detailed Error: 
```
E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.RuntimeException: java.io.FileNotFoundException: audience_network.dex
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeLoader(DynamicLoaderFactory.java:109)
        at com.facebook.ads.NativeAdBase.<init>(NativeAdBase.java:172)
        at com.facebook.ads.NativeAd.<init>(NativeAd.java:66)
        at com.dsi.facebook_audience_network.FacebookNativeAdView.<init>(FacebookNativeAdPlugin.java:69)
        at com.dsi.facebook_audience_network.FacebookNativeAdPlugin.create(FacebookNativeAdPlugin.java:39)
        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:143)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
        at android.app.Dialog.show(Dialog.java:302)
        at android.app.Presentation.show(Presentation.java:249)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:79)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:203)
        at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:142)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.io.FileNotFoundException: audience_network.dex
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:755)
        at android.content.res.AssetManager.open(AssetManager.java:732)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.createInMemoryClassLoader(DynamicLoaderFactory.java:160)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeAdsSdkClassLoader(DynamicLoaderFactory.java:123)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.makeLoader(DynamicLoaderFactory.java:101)
        at com.facebook.ads.NativeAdBase.<init>(NativeAdBase.java:172) 
        at com.facebook.ads.NativeAd.<init>(NativeAd.java:66) 
        at com.dsi.facebook_audience_network.FacebookNativeAdView.<init>(FacebookNativeAdPlugin.java:69) 
        at com.dsi.facebook_audience_network.FacebookNativeAdPlugin.create(FacebookNativeAdPlugin.java:39) 
        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:143) 
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407) 
        at android.app.Dialog.show(Dialog.java:302) 
        at android.app.Presentation.show(Presentation.java:249) 
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:79) 
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48) 
        at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:203) 
        at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:142) 
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201) 
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88) 
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-05-08 22:41:38.002 758-758/? D/SurfaceFlinger: duplicate layer name: changing Display Root to Display Root#1
2019-05-08 22:41:38.002 22119-22190/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.io.FileNotFoundException: audience_network.dex, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302)
    <asynchronous suspension>
    #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:596)
    <asynchronous suspension>
    #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:521)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189)
    <asynchronous suspension>
    #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170)
    #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1629)
    #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259)
    #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #10     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #21     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199)
    #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #25     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737)
    #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #27     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385)
    #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
    #32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:436)
    #33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212)
    #34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644)
    #38     _RenderProxyBox&RenderBox&RenderObje
```

**Comment by karnadii** [comment]
previously I using classpath 'com.android.tools.build:gradle:3.2.1' there is no error, after i upgrade to 3.3.2 I got this error.

**Comment by yunusemrecetin** [comment]
I don't use native ads but I got this error, you find any solution?

**Comment by SachinGanesh** [comment]
This is not an issue with the plugin. I was skipping target platform 'arm64-v8a' while building app in release mode.
